---
format: pdf
editor: visual
toc: false
bibliography: ../Supp_files/Morphology.bib
link-citations: true
csl: ../Supp_files/methods-in-ecology-and-evolution.csl
---

# Author information

Aaron A Skinner

Biodiversity Research Centre, University of British Columbia, Canada

skinnerayayron93\@gmail.com

# Letter

To whom it may concern,\
\
Thank you for your consideration of my article 'Beyond Bergmann and Allen: A Unified Framework for Thermoregulatory Morphology'. Within, I propose a new ecogeographical rule, the 'Thermo-Morpho Rule', which views size and shape as complementary axes of thermoregulatory adaptation. The rule calls for the unification of Bergmann's and Allen's rules, as both are governed by the same biophysical principle – that surface area to volume ratios mediate heat exchange.

# Synopsis

I begin with a review of the literature in the last 5 years to determine how often Bergmann's and Allen's rules have been analyzed in concert vs. in isolation. Of 86 papers that met the criteria for inclusion, half analyzed Bergmann's and Allen's rules in isolation, highlighting the need for a unified approach. I then highlight what we risk by analyzing these rules in isolation. Specifically, I argue that studies focusing on one rule or the other, but not both in concert, are unable to consider fundamental, biologically compelling processes likely to underpin thermoregulation, including 1) trade-offs - where the studied trait (e.g., body size) is functionally constrained and thus doesn’t respond to temperature; 2) complementarity - combined changes to size and shape that together constitute important adjustments to the surface area–to–volume ratio, and finally, 3) interactions - codependency between size and shape that jointly determine organismal response across temperature gradients.

In the final section, I argue that the potential for trade-offs, complementarity, and interactions is not restricted to morphology, but also extends to physiology, coloration, phenology, and behavior to meet thermoregulatory needs [e.g. trade-offs in @briscoeBergmannMeetsScholander2015; complementarity in @he2023global; and interactions in @playa-montmanyBehaviouralPhysiologicalResponses2023]. Thus, a natural next step is to formalize a broader Thermo-Adaptive Framework, encompassing any adaptive thermoregulatory approach. This framework is not an explicit rule that can be tested in the way that the Thermo-Morpho rule could be, but is better regarded as a conceptual framework that highlights the potential for trade-offs, complementarity, and interactions amongst adaptive thermoregulatory approaches. This paper serves as a call to action that will help sharpen scientists' predictions of biological responses to a warming world.

# Background

Several important reviews cover adherence to (or lack thereof) Bergmann's rule [@ashtonPatternsWithinSpeciesBody2002; @riemerNoGeneralRelationship2018], potential mechanisms [@yom-tovRecentSpatialTemporal2011], and implications in the face of climate change and species invasions [@gardnerDecliningBodySize2011; @teplitskyClimateWarmingBergmanns2014; @guoApplyingBergmannsRule2025]. Allen's rule has received less attention than Bergmann's rule, although @tattersallEvolutionAvianBill2017 extensively discusses the role of the avian bill in thermoregulation, and @rydingShapeshiftingChangingAnimal2021 provides an excellent review of Allen's rule and its applications in the Anthropocene. There have been several empirical global tests of Bergmann's rule [e.g. @he2023global; @skinnerEnvironmentalGeographicConditions2025], Allen's rule [e.g. @alhajeriGlobalTestAllens2020], along with several recent large-scale studies that jointly analyzed both rules [@frohlichAllometryRevealsTradeoffs2023; @baldwinComplementarityAllensBergmanns2023; @youngfleshAbioticConditionsShape2022].

Given their shared thermoregulatory basis, some authors have discussed the interrelatedness of ecogeographical rules [e.g., @ashtonAreEcologicalEvolutionary2001; @gastonEcogeographicalRulesElements2008], but none have explicitly argued for their joint and integrated analysis. That being said, the importance of a joint analytical approach is underscored by recent empirical work providing compelling evidence for the existence of trade-offs, complementarity, and interactions across large spatial and taxonomic scales [@frohlichAllometryRevealsTradeoffs2023; @baldwinComplementarityAllensBergmanns2023]. However, these papers did not leverage the broader literature to provide a unifying thermal-morphological framework.

The present Perspective aims to address this gap by highlighting 1) the current isolated treatment of Bergmann's and Allen's rules, 2) the conceptual importance of a joint approach, and 3) how the concepts of trade-offs, complementarity, and interactions extend beyond morphology. To date, no review has examined how often Bergmann's and Allen's rules have been studied together, or proposed a unified framework linking size, shape, and thermoregulatory capacity. In doing so, this work highlights both the conceptual disconnect in the literature and the analytical opportunities of studying multiple traits jointly.

# Questions for the editor

If the editors think this paper has potential for publication in *Nature Ecology and Evolution*, I seek their guidance regarding the optimal form and content of the final paper. The current paper has elements of both a review and perspective, and I am not sure which would be a better fit for the journal. If the editors believe that the present contribution should be broadened (e.g. for a review), I've included some areas that I think would be a constructive expansion:

1.  a quantitative synthesis of how frequently the 50% of studies that examined both Bergmann's and Allen's rules tested for trade-offs, complementarity, or interactions, versus simply testing the two rules in parallel;

2.  an assessment of how frequently studies in our lit review extended analyses to physiology, coloration, phenology, and behavior;

3.  discussion of data and design needs to test the Thermo-Morpho Rule and the broader Thermo-Adaptive Framework (e.g., intra- vs inter-specific scales);

4.  a synthesis of conservation implications.

Thank you very much for your consideration of this paper.

# Acknowledgements

Thank you to Justin Baldwin and Arkadiusz Fröhlich for permitting the use of their excellent conceptual figures. Thank you to M Lynne Cooper for her help and advice throughout the review process, as well as important feedback on earlier versions of this article.

{{< pagebreak >}}

# References
